### PR TITLE
Fixes units for filesizes in index.htm

### PR DESCRIPTION
**Pull request by ccapitalK**
Fixes a small error that I noticed when viewing the website.

### CODE REVIEW

**Comment by ccapitalK** [comment]
I just realized that this may be European decimal notation, if that is the case then please feel free to discard this PR.

**Comment by ikskuh** [comment]
> I just realized that this may be European decimal notation, if that is the case then please feel free to discard this PR.

Or i should've known. I would go for `XX,YYY byte` instead of `XX.YYY kilobyte` as it's shorter.

**Comment by ccapitalK** [comment]
Ok, I've updated the PR.

**Comment by ikskuh** [comment]
Thanks! :heart:

**Pull request merged**
